defaults:
  - base_dataset
  - view_sampler: bounded
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_dl3dv

name: dl3dv
roots: [datasets/dl3dv]

input_image_shape: [256, 256]
original_image_shape: [270, 480]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 100.0
