defaults:
  - base_dataset
  - view_sampler: bounded
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_re10k

name: re10k
roots: [datasets/re10k]

input_image_shape: [256, 256]
original_image_shape: [360, 640]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e10
max_fov: 100.0
